"""Emitter for the Phase D general-header reference test.

Reads the fixtures under tests/fixtures/av1-inter (each an untouched libaom
encode plus dav1d's native planes) and writes
av1_inter_reference_wbtest.mbt.

The template uses @TOKEN@ substitution rather than Python % formatting because
the MoonBit assertions contain their own %@ / %d format specifiers.
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIX = os.path.join(ROOT, "tests", "fixtures", "av1-inter")
OUT = os.path.join(ROOT, "av1_inter_reference_wbtest.mbt")

WIDTH = HEIGHT = 64
PLANE = WIDTH * HEIGHT + 2 * (WIDTH // 2) * (HEIGHT // 2)
NAMES = ("general_inter_64x64", "inter_minimal_64x64")

SPECS = {
    "general_inter_64x64": {
        "order_hint": "true",
        "warped": "true",
        "dual": "true",
        "ref_mvs": "true",
        "hint_bits": "7",
        "inter_order_hint": "1",
        "switchable_motion": "true",
        "key_bytes": "9",
        "inter_bytes": "15",
    },
    # --enable-order-hint=0 and --enable-warped-motion=0 turn each of those
    # frame-header fields into a derivation rather than a read, so the same
    # assertions prove the gates as well as the grammar.
    "inter_minimal_64x64": {
        "order_hint": "false",
        "warped": "false",
        "dual": "false",
        "ref_mvs": "false",
        "hint_bits": "0",
        "inter_order_hint": "0",
        "switchable_motion": "false",
        "key_bytes": "9",
        "inter_bytes": "14",
    },
}

HEADER = (
    "/// Generated by scripts/emit-av1-inter-test.py from\n"
    "/// scripts/generate-av1-inter-reference.py fixtures.\n"
    "///\n"
    "/// General (non reduced-still) AV1 headers carrying real inter frames, checked\n"
    "/// field-by-field against the FFmpeg `trace_headers` transcripts in\n"
    "/// tests/fixtures/av1-inter, plus dav1d's native planes for the key frame the\n"
    "/// intra pipeline can already reconstruct. The inter frame in each fixture must\n"
    "/// parse completely and then be refused at reconstruction: that refusal is the\n"
    "/// Phase D boundary, not a failure.\n"
)

HELPERS = r"""
///|
fn av1_inter_expand(runs : Array[Int]) -> Array[Int] {
  let out : Array[Int] = []
  let mut i = 0
  while i < runs.length() {
    let value = runs[i]
    let count = runs[i + 1]
    for _ in 0..<count {
      out.push(value)
    }
    i = i + 2
  }
  out
}

///|
/// dav1d's fixture planes are concatenated row-packed; copy one plane out.
fn av1_inter_slice(source : Array[Int], start : Int, end : Int) -> Array[Int] {
  Array::makei(end - start, i => source[start + i])
}

///|
/// Parse both frame headers of a fixture against one shared reference buffer,
/// the way a video decoder walks a temporal unit.
fn av1_inter_parse(
  obu : Array[Byte],
  label : String,
) -> (Av1SequenceInfo, Array[Av1FrameHeaderInfo], Av1FrameMap) raise {
  let seq = match av1_sequence_info(obu) {
    Some(value) => value
    None => fail(label + ": no sequence header")
  }
  let map = av1_frame_map()
  let payloads = av1_obu_payloads(obu, 6)
  assert_eq(payloads.length(), 2)
  let headers : Array[Av1FrameHeaderInfo] = []
  for payload in payloads {
    headers.push(match av1_parse_stage1_frame(payload, seq, allow_highbd=true, map=map) {
      Some(value) => value
      None => fail(label + ": frame header rejected")
    })
  }
  (seq, headers, map)
}
"""

TEST_TEMPLATE = r"""
///|
test "@NAME@: general frame headers parse and the key frame matches dav1d" {
  let (seq, headers, map) = av1_inter_parse(@NAME@_obu, "@NAME@")
  assert_eq(seq.reduced_still_picture_header, false)
  assert_eq(seq.enable_order_hint, @ORDER_HINT@)
  assert_eq(seq.enable_warped_motion, @WARPED@)
  assert_eq(seq.enable_dual_filter, @DUAL@)
  assert_eq(seq.enable_ref_frame_mvs, @REF_MVS@)
  assert_eq(seq.seq_force_screen_content_tools, av1_select_screen_content_tools)
  assert_eq(seq.seq_force_integer_mv, av1_select_integer_mv)
  assert_eq(seq.frame_id_numbers_present, false)
  assert_eq(seq.order_hint_bits, @HINT_BITS@)
  assert_eq(seq.use_128x128_superblock, true)
  assert_eq(seq.enable_superres, false)

  let key = headers[0]
  assert_eq(key.frame_type, av1_key_frame)
  assert_eq(key.frame_is_intra, true)
  assert_eq(key.show_frame, true)
  // A showing key frame is error resilient by bitstream requirement (AV1 6.4.2).
  assert_eq(key.error_resilient, true)
  assert_eq(key.primary_ref_frame, av1_primary_ref_none)
  assert_eq(key.refresh_frame_flags, 255)
  assert_eq(key.force_integer_mv, 1)
  assert_eq(key.order_hint, 0)
  assert_eq(key.frame_width, 64)
  assert_eq(key.upscaled_width, 64)
  assert_eq(key.frame_height, 64)
  assert_eq(key.superres_denom, 8)
  assert_eq(key.render_width, 64)
  assert_eq(key.base_q_idx, 49)
  assert_eq(key.header_bytes, @KEY_BYTES@)

  let inter = headers[1]
  assert_eq(inter.frame_type, av1_inter_frame)
  assert_eq(inter.frame_is_intra, false)
  assert_eq(inter.show_frame, true)
  assert_eq(inter.error_resilient, false)
  assert_eq(inter.order_hint, @INTER_ORDER_HINT@)
  assert_eq(inter.primary_ref_frame, av1_primary_ref_none)
  assert_eq(inter.refresh_frame_flags, 2)
  assert_eq(inter.base_q_idx, 128)
  assert_eq(inter.header_bytes, @INTER_BYTES@)
  assert_eq(inter.ref_frame_idx.length(), av1_refs_per_frame)
  for slot in inter.ref_frame_idx {
    // frame_refs_short_signaling is 0 here and every name points at slot 0.
    assert_eq(slot, 0)
  }
  assert_eq(inter.allow_high_precision_mv, false)
  // A switchable frame defers the interpolation filter to each block.
  assert_eq(inter.interpolation_filter, 4)
  assert_eq(inter.allow_warped_motion, @WARPED@)
  assert_eq(inter.use_ref_frame_mvs, @REF_MVS@)
  assert_eq(inter.is_motion_mode_switchable, @SWITCHABLE@)
  assert_eq(inter.reference_select, false)
  assert_eq(inter.skip_mode_present, false)
  assert_eq(inter.allow_intrabc, false)
  for typ in inter.gm_type {
    assert_eq(typ, av1_gm_identity)
  }
  for bias in inter.ref_frame_sign_bias {
    assert_eq(bias, 0)
  }

  // Parsing alone must not touch the buffer: only reconstruction stores.
  assert_eq(av1_frame_map_show(map, 0) is None, true)
  let decoded = match av1_decode_frame_planes(@NAME@_obu, map=map) {
    Some(value) => value
    None => fail("@NAME@: key frame decode rejected")
  }
  // dav1d's native planes are stored row-packed per plane, the same view
  // `av1_frame_crop` produces from the MI-padded coding layout.
  let reference = av1_inter_expand(@NAME@_frame0_reference)
  let chroma = @PLANE@ / 6
  assert_eq(av1_frame_crop(decoded, 0), av1_inter_slice(reference, 0, @PLANE@ - chroma * 2))
  assert_eq(av1_frame_crop(decoded, 1), av1_inter_slice(reference, @PLANE@ - chroma * 2, @PLANE@ - chroma))
  assert_eq(av1_frame_crop(decoded, 2), av1_inter_slice(reference, @PLANE@ - chroma, @PLANE@))
  // Every slot a key frame claims now shares the same decoded picture.
  let stored = match av1_frame_map_show(map, 0) {
    Some(value) => value
    None => fail("@NAME@: key frame not stored")
  }
  assert_eq(stored.upscaled_width, 64)
  assert_eq(stored.frame_height, 64)
  assert_eq(stored.bit_depth, 8)
  assert_eq(stored.frame_type, av1_key_frame)
  for slot in 0..<av1_num_ref_frames {
    assert_eq(av1_frame_map_show(map, slot) is None, false)
  }
}
"""


def byte_literal(data):
    rows = []
    for start in range(0, len(data), 12):
        rows.append(
            "  " + " ".join("b'\\x%02X'," % b for b in data[start : start + 12])
        )
    return "\n".join(rows)


def rle(samples):
    out = []
    i = 0
    while i < len(samples):
        value = samples[i]
        run = 1
        while (
            i + run < len(samples)
            and samples[i + run] == value
            and run < 9999
        ):
            run += 1
        out.append("%d, %d," % (value, run))
        i += run
    return "\n  ".join(out)


def main():
    parts = [HEADER]
    for name in NAMES:
        obu = open(os.path.join(FIX, name + ".obu"), "rb").read()
        ref = open(os.path.join(FIX, name + ".reference.yuv"), "rb").read()
        assert len(ref) == 2 * PLANE, len(ref)
        parts.append(
            "\n///|\nlet %s_obu : Array[Byte] = [\n%s\n]\n"
            % (name, byte_literal(obu))
        )
        # Frame 1 is inter: its planes become the ground truth once motion
        # compensation lands, and embedding them before then only adds dead
        # literals. Frame 0 is the key frame the intra pipeline can rebuild.
        for index in range(1):
            plane = ref[index * PLANE : (index + 1) * PLANE]
            parts.append(
                "\n///|\n/// dav1d native planes for %s frame %d.\n"
                "let %s_frame%d_reference : Array[Int] = [\n  %s\n]\n"
                % (name, index, name, index, rle(plane))
            )
    parts.append(HELPERS)
    for name in NAMES:
        spec = SPECS[name]
        body = TEST_TEMPLATE.replace("@NAME@", name)
        for token, value in [
            ("@ORDER_HINT@", spec["order_hint"]),
            ("@WARPED@", spec["warped"]),
            ("@DUAL@", spec["dual"]),
            ("@REF_MVS@", spec["ref_mvs"]),
            ("@HINT_BITS@", spec["hint_bits"]),
            ("@INTER_ORDER_HINT@", spec["inter_order_hint"]),
            ("@SWITCHABLE@", spec["switchable_motion"]),
            ("@KEY_BYTES@", spec["key_bytes"]),
            ("@INTER_BYTES@", spec["inter_bytes"]),
            ("@PLANE@", str(PLANE)),
        ]:
            body = body.replace(token, value)
        leftover = [
            line.strip() for line in body.splitlines() if "@NAME" in line or "@KEY" in line
        ]
        assert not leftover, leftover
        parts.append(body)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(parts))
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
