#!/usr/bin/env python3
"""Real libaom 10-bit 4:2:2/4:4:4 superres with independent dav1d planes.

--check regenerates in temporary storage and only compares repository bytes.
Tool executables may be overridden; no machine-specific paths are recorded.
"""
from pathlib import Path
import argparse
import hashlib
import json
import math
import re
import shutil
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "tests/fixtures/av1-superres-sampling"
WB = ROOT / "av1_superres_sampling_reference_wbtest.mbt"


def run(args, cwd):
    proc = subprocess.run(args, cwd=cwd, capture_output=True)
    if proc.returncode:
        raise RuntimeError(proc.stderr.decode("utf-8", errors="replace"))
    return proc.stdout, proc.stderr


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    for tool in ("aomenc", "dav1d", "ffmpeg"):
        parser.add_argument("--" + tool, default=tool)
    options = parser.parse_args()
    tools = {tool: shutil.which(getattr(options, tool)) for tool in ("aomenc", "dav1d", "ffmpeg")}
    formatter = shutil.which("moonfmt")
    if not all(tools.values()):
        raise SystemExit("aomenc, dav1d and ffmpeg must be available on PATH or supplied explicitly")
    if not formatter:
        raise SystemExit("moonfmt from the repository's pinned MoonBit toolchain is required")
    files = {}
    records = []
    tests = ["// Generated by scripts/generate-av1-superres-sampling-reference.py.\n"]
    with tempfile.TemporaryDirectory(prefix="pixelforge-superres-sampling-") as temporary:
        directory = Path(temporary)
        for sampling, profile, sub_x in (("422", 2, 1), ("444", 1, 0)):
            name = "superres_" + sampling + "_10bit_denom9"
            values = []
            for plane in range(3):
                width = 96 if plane == 0 else 96 >> sub_x
                for y in range(64):
                    for x in range(width):
                        value = 512 + 155 * math.sin(x * .17 + plane) + 96 * math.cos(y * .23 - plane) + ((x * 7 + y * 11) % 43)
                        values.append(max(0, min(1023, round(value))))
            raw = struct.pack("<" + "H" * len(values), *values)
            (directory / (name + ".input.yuv")).write_bytes(raw)
            flags = ["--codec=av1", "--obu", "--i" + sampling, "--width=96", "--height=64",
                     "--bit-depth=10", "--input-bit-depth=10", "--profile=" + str(profile),
                     "--fps=1/1", "--limit=1", "--passes=1", "--lag-in-frames=0", "--threads=1",
                     "--cpu-used=4", "--end-usage=q", "--cq-level=24",
                     "--superres-mode=1", "--superres-denominator=9", "--superres-kf-denominator=9",
                     "--enable-cdef=0", "--enable-restoration=0", "--loopfilter-control=0",
                     "--enable-intrabc=0", "--enable-palette=0", "--use-intra-dct-only=1",
                     "--enable-qm=0", "--enable-tx64=0", "--deltaq-mode=0", "--sb-size=64",
                     "--min-partition-size=16", "--max-partition-size=32", "--disable-warning-prompt",
                     "-o", name + ".obu", name + ".input.yuv"]
            run([tools["aomenc"], *flags], directory)
            decode = ["-q", "--threads=1", "--framedelay=1", "-i", name + ".obu", "--muxer=yuv", "-o", name + ".reference.yuv"]
            run([tools["dav1d"], *decode], directory)
            _, trace = run([tools["ffmpeg"], "-v", "verbose", "-i", name + ".obu", "-c:v", "copy", "-bsf:v", "trace_headers", "-f", "null", "-"], directory)
            text = trace.decode("utf-8", errors="replace")
            if not re.search(r"use_superres\s+[^=\n]+=\s*1", text) or not re.search(r"coded_denom\s+[^=\n]+=\s*0", text):
                raise ValueError("Encoder did not select denominator 9")
            trace = "\n".join(line[line.index("]") + 1:].strip() for line in text.splitlines() if line.startswith("[trace_headers")) + "\n"
            obu = (directory / (name + ".obu")).read_bytes()
            native = (directory / (name + ".reference.yuv")).read_bytes()
            assert len(native) == len(raw)
            reference = struct.unpack("<" + "H" * (len(native) // 2), native)
            for suffix, data in ((".input.yuv", raw), (".obu", obu), (".reference.yuv", native), (".trace.txt", trace.encode("utf-8"))):
                files[name + suffix] = data
            records.append({"name": name, "dimensions": [96, 64], "bit_depth": 10, "subsampling": [sub_x, 0],
                            "denominator": 9, "encoder": ["aomenc", *flags], "decoder": ["dav1d", *decode],
                            "sha256": {suffix: hashlib.sha256(data).hexdigest() for suffix, data in (("obu", obu), ("native", native))}})
            tests += ["///|\n", f"test \"superres sampling {sampling}: independent native planes\" {{\n",
                      "  let data : Array[Byte] = [\n"]
            for start in range(0, len(obu), 16):
                tests.append("    " + ", ".join(f"b'\\x{v:02X}'" for v in obu[start:start + 16]) + ",\n")
            tests += ["  ]\n", "  let expected : Array[Int] = [\n"]
            for start in range(0, len(reference), 16):
                tests.append("    " + ", ".join(map(str, reference[start:start + 16])) + ",\n")
            tests += ["  ]\n", "  let frame = av1_decode_frame_planes(data).unwrap()\n",
                      f"  assert_eq((frame.width, frame.height, frame.sub_x, frame.sub_y), (96, 64, {sub_x}, 0))\n",
                      "  let mut offset = 0\n  for plane in 0..<3 {\n    let actual = av1_frame_crop(frame, plane)\n",
                      "    for i in 0..<actual.length() { assert_eq((plane, i, actual[i]), (plane, i, expected[offset+i])) }\n",
                      "    offset = offset + actual.length()\n  }\n  assert_eq(offset, expected.length())\n}\n\n"]
        versions = {}
        for tool, args in (("aomenc", ["--help"]), ("dav1d", ["--version"]), ("ffmpeg", ["-version"])):
            output, errors = run([tools[tool], *args], directory)
            text = (output + errors).decode("utf-8", errors="replace")
            version = re.search(r"\bv?(\d+\.\d+\.\d+(?:-[A-Za-z0-9._]+)?)", text)
            if not version:
                raise ValueError("Missing tool version: " + tool)
            versions[tool] = version[1]
        files["manifest.json"] = (json.dumps({"tools": versions, "fixtures": records}, indent=2) + "\n").encode("utf-8")
    files["README.md"] = b"# Superres with independent chroma axes\n\nReal libaom streams at 10-bit, denominator 9, 4:2:2 and 4:4:4. Expected native planes come from dav1d. Regenerate using `python scripts/generate-av1-superres-sampling-reference.py`; `--check` compares in temporary storage without rewriting repository files. Tool paths resolve from PATH or CLI options. The manifest records commands and byte hashes.\n"
    outputs = {OUTPUT / name: data for name, data in files.items()}
    formatted = subprocess.run([formatter, "-"], input="".join(tests).encode("utf-8"), capture_output=True, check=True)
    outputs[WB] = formatted.stdout.replace(b"\r\n", b"\n")
    for path, data in outputs.items():
        if options.check:
            actual = path.read_bytes()
            if path.suffix in (".mbt", ".md", ".json", ".txt"):
                actual = actual.replace(b"\r\n", b"\n")
            if actual != data:
                raise SystemExit("Stale: " + str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print("Verified 4:2:2 and 4:4:4 native superres fixtures")


if __name__ == "__main__":
    main()
