"""Generate the chroma-subsampling white-box test.

Two reduced-still aomenc encodes share one 64x64 luma plane and differ only in
chroma format:

* ``sub444.obu``  ``--i444`` -> profile 1, subsampling (0, 0), U and V at 64x64
* ``sub422.obu``  ``--i422`` -> profile 2, subsampling (1, 0), U and V at 32x64

Expectations are dav1d 1.2.1 output written with ``--muxer yuv``, so the truth
plane sizes are 4096+4096+4096 and 4096+2048+2048 respectively.
"""

import sys

DIR = "tests/fixtures/av1-subsampling"
OUT = "av1_subsampling_wbtest.mbt"


def moon_bytes(data, per_line=12):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append(
            "    " + ", ".join("b'\\x%02X'" % b for b in chunk) + ","
        )
    return "\n".join(lines)


def digest(samples):
    h = 0
    for i, s in enumerate(samples):
        v = s & 0xFF
        h ^= (v + (i & 0xFF))
        h = ((h << 5) & 0xFFFFFF) | ((h >> 19) & 0x1F)
        h &= 0xFFFFFF
    return h


HEADER = '''/// Chroma-subsampling tests.
///
/// Generated by scripts/generate-av1-subsampling-test.py from the fixtures in
/// tests/fixtures/av1-subsampling. Every expectation is dav1d 1.2.1 output.
///
/// Both streams carry the same 64x64 luma plane and the same tile syntax; only
/// the chroma format differs, so a wrong plane geometry shows up as a chroma
/// digest mismatch rather than a decode failure.

///|
fn av1_sub444_stream() -> Array[Byte] {
  [
'''

MIDDLE = '''  ]
}

///|
fn av1_sub422_stream() -> Array[Byte] {
  [
'''

THIRD = '''  ]
}

///|
/// 4:4:4 with an active chroma CDEF strength (cdef_uv_pri_strength = 10) and a
/// noisy luma plane, which is what exercises the chroma CDEF block geometry.
fn av1_sub444_cdef_stream() -> Array[Byte] {
  [
'''

FOOTER = '''  ]
}

///|
/// Profile and subsampling come from the sequence header color config: profile
/// 1 is 4:4:4 with no monochrome bit, and profile 2 at eight bits is 4:2:2.
test "sequence color config distinguishes 4:4:4 and 4:2:2" {
  let seq444 = av1_sequence_info(av1_sub444_stream()).unwrap()
  assert_eq(seq444.profile, 1)
  assert_eq(seq444.monochrome, false)
  assert_eq(seq444.subsampling_x, false)
  assert_eq(seq444.subsampling_y, false)
  let seq422 = av1_sequence_info(av1_sub422_stream()).unwrap()
  assert_eq(seq422.profile, 2)
  assert_eq(seq422.monochrome, false)
  assert_eq(seq422.subsampling_x, true)
  assert_eq(seq422.subsampling_y, false)
}

///|
/// 4:4:4 planes are all 64x64 and match dav1d sample for sample.
test "4:4:4 stream matches dav1d pixel truth" {
  let frame = av1_decode_frame_planes(av1_sub444_stream()).unwrap()
  let y = av1_frame_crop(frame, 0)
  let u = av1_frame_crop(frame, 1)
  let v = av1_frame_crop(frame, 2)
  assert_eq(y.length(), 4096)
  assert_eq(u.length(), 4096)
  assert_eq(v.length(), 4096)
  assert_eq(av1_plane_digest(y), 12264532)
  assert_eq(av1_plane_digest(u), 13617159)
  assert_eq(av1_plane_digest(v), 5016429)
  assert_eq(u[0], 90)
  assert_eq(u[1], 92)
  assert_eq(u[2], 94)
  assert_eq(v[0], 140)
  assert_eq(v[64], 142)
}

///|
/// 4:2:2 keeps full vertical chroma resolution: U and V are 32x64 and match
/// dav1d, including the vertical ramp that a 4:2:0 reading would flatten.
test "4:2:2 stream matches dav1d pixel truth" {
  let frame = av1_decode_frame_planes(av1_sub422_stream()).unwrap()
  let y = av1_frame_crop(frame, 0)
  let u = av1_frame_crop(frame, 1)
  let v = av1_frame_crop(frame, 2)
  assert_eq(y.length(), 4096)
  assert_eq(u.length(), 2048)
  assert_eq(v.length(), 2048)
  assert_eq(av1_plane_digest(y), 14670826)
  assert_eq(av1_plane_digest(u), 16427600)
  assert_eq(av1_plane_digest(v), 3466790)
  assert_eq(u[0], 90)
  assert_eq(u[1], 94)
  assert_eq(u[2], 98)
  assert_eq(v[0], 140)
  assert_eq(v[32], 142)
}

///|
/// Active chroma CDEF on a 4:4:4 plane: the filter must run on full-resolution
/// chroma with the 8x8 luma-equivalent block grid. The chroma head samples
/// differ from the source ramp precisely because the filter changed them.
test "4:4:4 stream with active chroma CDEF matches dav1d pixel truth" {
  let frame = av1_decode_frame_planes(av1_sub444_cdef_stream()).unwrap()
  let y = av1_frame_crop(frame, 0)
  let u = av1_frame_crop(frame, 1)
  let v = av1_frame_crop(frame, 2)
  assert_eq(y.length(), 4096)
  assert_eq(u.length(), 4096)
  assert_eq(v.length(), 4096)
  assert_eq(av1_plane_digest(y), 5689114)
  assert_eq(av1_plane_digest(u), 8930597)
  assert_eq(av1_plane_digest(v), 7610770)
  assert_eq(u[0], 92)
  assert_eq(u[1], 93)
  assert_eq(u[2], 94)
  assert_eq(v[0], 142)
}
'''


def main():
    s444 = open("%s/sub444.obu" % DIR, "rb").read()
    s422 = open("%s/sub422.obu" % DIR, "rb").read()
    cdef = open("%s/sub444cdef.obu" % DIR, "rb").read()
    body = (
        HEADER
        + moon_bytes(s444)
        + "\n"
        + MIDDLE
        + moon_bytes(s422)
        + "\n"
        + THIRD
        + moon_bytes(cdef)
        + "\n"
        + FOOTER
    )
    open(OUT, "w", newline="\n").write(body)
    print("wrote", OUT)
    t = open("%s/truth444.yuv" % DIR, "rb").read()
    print("  444 Y=%d U=%d V=%d" % (digest(t[:4096]), digest(t[4096:8192]),
                                   digest(t[8192:12288])))
    t = open("%s/truth422.yuv" % DIR, "rb").read()
    print("  422 Y=%d U=%d V=%d" % (digest(t[:4096]), digest(t[4096:6144]),
                                   digest(t[6144:8192])))


if __name__ == "__main__":
    sys.exit(main())
