#!/usr/bin/env python3
"""Extract all palette CDFs from pinned original AOM and cross-check cached Go.

Only the marked CDF section of the specified MoonBit source is regenerated.
--check parses the current section and checks all 107 complete CDF rows without
writing files, formatting a package, compiling Moon or accessing the network.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
REVISION = "8e7b6a567df174d795479b92b4ac766d271add73"
BEGIN = "// BEGIN GENERATED PALETTE CDFS"
END = "// END GENERATED PALETTE CDFS"


def braced(text: str, start: int) -> str:
    opening = text.index("{", start)
    depth = 1
    end = opening + 1
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[opening:end]


def original_tables(directory: Path) -> dict[str, list]:
    revision = subprocess.run(["git", "-C", str(directory), "rev-parse", "HEAD"],
                              check=True, capture_output=True, text=True).stdout.strip()
    if revision != REVISION:
        raise RuntimeError(f"unexpected AOM revision: {revision}")
    source = subprocess.run(["git", "-C", str(directory), "show", f"{REVISION}:av1/common/entropymode.c"],
                            check=True, capture_output=True).stdout.decode()
    result = {}
    for name in ("y_mode", "uv_mode", "y_size", "uv_size", "y_color_index", "uv_color_index"):
        start = source.index("default_palette_" + name + "_cdf")
        body = braced(source, source.index("=", start))
        rows = []
        for count, values in re.findall(r"AOM_CDF(\d+)\(([^)]*)\)", body):
            row = [int(value.strip()) for value in values.split(",")]
            if len(row) != int(count) - 1:
                raise RuntimeError(f"malformed original CDF: {name}")
            rows.append(row + [32768, 0])
        if name == "y_mode":
            assert len(rows) == 21
            result[name] = [rows[i:i + 3] for i in range(0, 21, 3)]
        elif name.endswith("color_index"):
            assert len(rows) == 35
            for i, row in enumerate(rows):
                assert len(row) == i // 5 + 3
            result[name.replace("color_index", "index")] = [rows[i:i + 5] for i in range(0, 35, 5)]
        else:
            assert len(rows) == (2 if name == "uv_mode" else 7)
            result[name] = rows
    return result


def cached_go_tables() -> dict[str, list]:
    text = "\n".join((ROOT / "_refs/go-av1/cdf" / name).read_text(encoding="utf-8")
                     for name in ("tables_mode_gen.go", "tables_palette_gen.go"))

    def get(name):
        match = re.search(r"var " + name + r" = [^{]+(\{[^\n]+\})", text)
        if match is None:
            raise RuntimeError(f"missing cached Go CDF: {name}")
        return json.loads(match.group(1).replace("{", "[").replace("}", "]"))

    return {
        "y_mode": get("DefaultPaletteYModeCdf"),
        "uv_mode": get("DefaultPaletteUvModeCdf"),
        "y_size": get("DefaultPaletteYSizeCdf"),
        "uv_size": get("DefaultPaletteUvSizeCdf"),
        "y_index": [get(f"DefaultPaletteSize{n}YColorCdf") for n in range(2, 9)],
        "uv_index": [get(f"DefaultPaletteSize{n}UvColorCdf") for n in range(2, 9)],
    }


def array_text(value: list, indent: int) -> str:
    if not isinstance(value[0], list):
        return "[" + ", ".join(str(item) for item in value) + "]"
    return "[\n" + "\n".join(" " * (indent + 2) + array_text(item, indent + 2) + "," for item in value) + "\n" + " " * indent + "]"


def generated(tables: dict[str, list]) -> str:
    output = [BEGIN, "// Generated by scripts/generate-av1-palette-tables.py.",
              f"// Original AOM {REVISION}, av1/common/entropymode.c:642-783.",
              "// Forward cumulative thresholds include terminal 32768 and update count 0."]
    for name, values in tables.items():
        typ = "Array[Array[Array[Int]]]" if name in ("y_mode", "y_index", "uv_index") else "Array[Array[Int]]"
        output += ["", "///|", f"fn av1_palette_{name}_cdfs() -> {typ} {{", "  " + array_text(values, 2), "}"]
    output += [END]
    return "\n".join(output)


def verify_moon(text: str, tables: dict[str, list]) -> None:
    for name, expected in tables.items():
        marker = f"fn av1_palette_{name}_cdfs()"
        body = braced(text, text.index(marker))[1:-1].strip()
        actual = json.loads(re.sub(r",\s*]", "]", body))
        if actual != expected:
            raise RuntimeError(f"MoonBit palette CDF mismatch: {name}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--aom-source", type=Path, default=Path(os.environ.get("TEMP", ".")) / "aom-ref-6693dbe8-0996-419e-94c4-cba21f4b7509")
    parser.add_argument("--target", type=Path, default=ROOT / "av1_palette.mbt")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    tables = original_tables(args.aom_source)
    if tables != cached_go_tables():
        raise RuntimeError("cached Go tables differ from pinned original AOM")
    text = args.target.read_text(encoding="utf-8")
    start, end = text.index(BEGIN), text.index(END) + len(END)
    if not args.check:
        text = text[:start] + generated(tables) + text[end:]
        args.target.write_text(text, encoding="utf-8", newline="\n")
    verify_moon(text, tables)
    print("Verified all 107 palette CDF rows against original AOM and cached Go; no Moon build")


if __name__ == "__main__":
    main()
