#!/usr/bin/env python3
"""Generate fixed-block 8/10/12-bit AC/lossless references with libaom and dav1d.

The input, untouched aomenc OBU output, and independently decoded full YUV planes
are retained beside a manifest. The generated MoonBit tests use those exact
planes with PixelForge's existing color conversion, avoiding a comparison with
ffmpeg's different YUV-to-RGB rounding. This is a fixed single-block fixture
corpus, not evidence of general AV1 support.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
import re
import shutil
import struct
import subprocess
import sys
from pathlib import Path


WIDTH = HEIGHT = 64
PATTERNS = {
    "y_cosine": {
        "y": "round(scale * (128 + 10*cos(pi*(x+0.5)/64)))",
        "u": "128*scale",
        "v": "128*scale",
    },
    "y_smooth_gradient": {
        "y": "round(scale * (96 + 40*(x+0.5)/64 + 24*(y+0.5)/64))",
        "u": "128*scale",
        "v": "128*scale",
    },
    "mixed_yuv": {
        "y": "round(scale * (128 + 8*cos(pi*(x+0.5)/64) + 6*cos(pi*(y+0.5)/64)))",
        "u": "round(scale * (136 + 7*cos(pi*(x+0.5)/32) + 4*cos(pi*(y+0.5)/32)))",
        "v": "round(scale * (120 + 5*cos(pi*(x+0.5)/32) - 6*cos(pi*(y+0.5)/32)))",
    },
}


def run(command: list[str], *, input_text: str | None = None) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(command, input=input_text, text=True, capture_output=True)
    if result.returncode:
        raise RuntimeError(f"command failed: {command!r}\n{result.stdout}\n{result.stderr}")
    return result


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def input_planes(pattern: str, bit_depth: int) -> list[list[int]]:
    scale = 1 << (bit_depth - 8)
    planes = []
    for plane, side in enumerate((64, 32, 32)):
        samples = []
        for y in range(side):
            for x in range(side):
                cx = math.cos(math.pi * (x + 0.5) / side)
                cy = math.cos(math.pi * (y + 0.5) / side)
                if pattern == "y_cosine":
                    sample = 128 + 10 * cx if plane == 0 else 128
                elif pattern == "y_smooth_gradient":
                    sample = 96 + 40 * (x + 0.5) / 64 + 24 * (y + 0.5) / 64 if plane == 0 else 128
                else:
                    sample = (128 + 8 * cx + 6 * cy, 136 + 7 * cx + 4 * cy, 120 + 5 * cx - 6 * cy)[plane]
                samples.append(round(scale * sample))
        planes.append(samples)
    return planes


def pack_planes(planes: list[list[int]], bit_depth: int) -> bytes:
    samples = list(itertools.chain.from_iterable(planes))
    return bytes(samples) if bit_depth == 8 else struct.pack(f"<{len(samples)}H", *samples)


def unpack_planes(data: bytes, bit_depth: int) -> list[list[int]]:
    expected = 6144 * (1 if bit_depth == 8 else 2)
    if len(data) != expected:
        raise RuntimeError(f"unexpected decoded size: {len(data)} != {expected}")
    samples = list(data) if bit_depth == 8 else list(struct.unpack("<6144H", data))
    if any(sample >= 1 << bit_depth for sample in samples):
        raise RuntimeError("decoded sample exceeds the coded bit depth")
    return [samples[:4096], samples[4096:5120], samples[5120:]]


def trace_value(trace: str, name: str) -> int:
    matches = re.findall(rf"\b{re.escape(name)}\s+[^=\n]+=\s*(-?\d+)", trace)
    if not matches or len(set(matches)) != 1:
        raise RuntimeError(f"missing or inconsistent trace value for {name}: {matches}")
    return int(matches[0])


def rle(samples: list[int]) -> list[int]:
    result = []
    for value, group in itertools.groupby(samples):
        result.extend((value, sum(1 for _ in group)))
    return result


def array(values: list[int], indent: str = "    ") -> str:
    rows = [indent + ", ".join(str(value) for value in values[i:i + 16]) + "," for i in range(0, len(values), 16)]
    return "[\n" + "\n".join(rows) + "\n" + indent[:-2] + "]"


def generated_test(cases: list[dict[str, object]]) -> str:
    source = """/// Generated by scripts/generate-av1-highbd-ac-reference.py.
/// Real libaom OBU streams and full dav1d planar references, stored losslessly
/// as value/count pairs. One 64x64 coding block uses DCT at q30 or 4x4 WHT
/// transforms for lossless q0; every decoded reference sample is retained.
fn av1_highbd_ac_expand(runs : Array[Int]) -> Array[Int] {
  let samples : Array[Int] = []
  for pair in 0..<(runs.length() / 2) {
    for _ in 0..<runs[pair * 2 + 1] {
      samples.push(runs[pair * 2])
    }
  }
  samples
}

///|
fn av1_highbd_ac_compare(
  stream : Array[Byte], bit_depth : Int, y_runs : Array[Int],
  u_runs : Array[Int], v_runs : Array[Int],
) -> Unit raise {
  let y_plane = av1_highbd_ac_expand(y_runs)
  let u_plane = av1_highbd_ac_expand(u_runs)
  let v_plane = av1_highbd_ac_expand(v_runs)
  assert_eq(y_plane.length(), 4096)
  assert_eq(u_plane.length(), 1024)
  assert_eq(v_plane.length(), 1024)
  let expected = av1_yuv420_highbd_to_rgba(
    64, 64, y_plane, u_plane, v_plane, bit_depth,
    full_range=false, matrix_coefficients=2,
  ).unwrap()
  let actual = av1_decode(stream).unwrap()
  for y in 0..<64 {
    for x in 0..<64 {
      assert_eq(actual.get_pixel(x, y), expected.get_pixel(x, y))
    }
  }
}
"""
    for case in cases:
        stream = case["stream"]
        assert isinstance(stream, bytes)
        rows = ["    " + ", ".join(f"b'\\x{value:02X}'" for value in stream[i:i + 12]) + "," for i in range(0, len(stream), 12)]
        source += f'\n///|\ntest "external libaom dav1d AC {case["name"]}" {{\n'
        source += "  let stream : Array[Byte] = [\n" + "\n".join(rows) + "\n  ]\n"
        for plane, samples in zip(("y", "u", "v"), case["planes"]):
            source += f"  let {plane}_runs : Array[Int] = " + array(rle(samples)) + "\n"
        source += f'  av1_highbd_ac_compare(stream, {case["bit_depth"]}, y_runs, u_runs, v_runs)\n}}\n'
    return source


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("tests/fixtures/av1-highbd-ac"))
    parser.add_argument("--test", type=Path, default=Path("av1_highbd_ac_reference_test.mbt"))
    parser.add_argument("--aomenc", default=shutil.which("aomenc") or "aomenc")
    parser.add_argument("--ffmpeg", default=shutil.which("ffmpeg") or "ffmpeg")
    parser.add_argument("--moonfmt", default=shutil.which("moonfmt") or "moonfmt")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    encoder_help = run([args.aomenc, "--help"])
    encoder_version = re.search(r"AOMedia Project AV1 Encoder[^\r\n]+", encoder_help.stdout + encoder_help.stderr)
    if encoder_version is None:
        raise RuntimeError("could not identify aomenc version")
    ffmpeg_version = run([args.ffmpeg, "-version"]).stdout.splitlines()
    records = []
    test_cases = []
    dav1d_version = None
    for bit_depth in (8, 10, 12):
        for pattern, quantizer in itertools.product(PATTERNS, (30, 0)):
            lossless = quantizer == 0
            name = f"{pattern}_{bit_depth}bit_q{quantizer}"
            input_path = args.out / f"{name}.input.yuv"
            obu_path = args.out / f"{name}.obu"
            reference_path = args.out / f"{name}.reference.yuv"
            inputs = input_planes(pattern, bit_depth)
            input_path.write_bytes(pack_planes(inputs, bit_depth))
            encode = [
                args.aomenc, "--debug", "--disable-warning-prompt", "--allintra", "--obu", "--i420",
                "--width=64", "--height=64", f"--profile={2 if bit_depth == 12 else 0}",
                f"--bit-depth={bit_depth}", f"--input-bit-depth={bit_depth}", "--fps=1/1", "--limit=1",
                "--cpu-used=0", "--threads=1", "--end-usage=q", f"--cq-level={quantizer}",
                f"--lossless={int(lossless)}", "--sb-size=64",
                "--tile-columns=0", "--tile-rows=0", "--aq-mode=0", "--deltaq-mode=0",
                "--enable-chroma-deltaq=0", "--enable-qm=0", "--enable-cdef=0", "--enable-restoration=0",
                "--enable-filter-intra=0", "--enable-intra-edge-filter=0", "--enable-angle-delta=0",
                "--enable-rect-partitions=0", "--enable-1to4-partitions=0", "--enable-ab-partitions=0",
                "--enable-smooth-intra=0", "--enable-paeth-intra=0", "--enable-palette=0",
                "--enable-flip-idtx=0", "--enable-tx64=1", "--enable-tx-size-search=0",
                "--use-intra-default-tx-only=1", "--min-partition-size=64", "--max-partition-size=64",
                "--enable-directional-intra=0", "--enable-cfl-intra=0", "--enable-intrabc=0",
                "--loopfilter-control=0", "-o", str(obu_path), str(input_path),
            ]
            run(encode)
            pixel_format = "yuv420p" if bit_depth == 8 else f"yuv420p{bit_depth}le"
            decode = [
                args.ffmpeg, "-hide_banner", "-loglevel", "verbose", "-y", "-c:v", "libdav1d",
                "-i", str(obu_path), "-frames:v", "1", "-f", "rawvideo", "-pix_fmt", pixel_format,
                str(reference_path),
            ]
            decoded = run(decode)
            decoder_versions = re.findall(r"libdav1d\s+([0-9][^\s]*)", decoded.stderr)
            if not decoder_versions:
                raise RuntimeError(f"{name}: libdav1d did not report its version")
            if dav1d_version is not None and dav1d_version != decoder_versions[0]:
                raise RuntimeError("libdav1d version changed during generation")
            dav1d_version = decoder_versions[0]
            trace_command = [
                args.ffmpeg, "-hide_banner", "-i", str(obu_path), "-c", "copy",
                "-bsf:v", "trace_headers", "-f", "null", "-",
            ]
            trace_result = run(trace_command)
            trace = trace_result.stderr
            fields = {
                name: trace_value(trace, name)
                for name in (
                    "reduced_still_picture_header", "use_128x128_superblock", "enable_cdef",
                    "enable_restoration", "enable_filter_intra", "enable_intra_edge_filter",
                    "base_q_idx", "color_range", "color_description_present_flag",
                    "seq_profile", "high_bitdepth", "mono_chrome", "max_frame_width_minus_1",
                    "max_frame_height_minus_1", "using_qmatrix",
                    "delta_q_y_dc.delta_coded", "delta_q_u_dc.delta_coded", "delta_q_u_ac.delta_coded",
                )
            }
            # Lossless headers infer ONLY_4X4 and delta_q_present=0; those
            # fields need not be explicitly present in trace_headers output.
            for field in ("tx_mode", "delta_q_present"):
                if re.search(rf"\b{field}\s+[^=\n]+=", trace):
                    fields[field] = trace_value(trace, field)
                elif not lossless:
                    raise RuntimeError(f"{name}: missing {field} in lossy header")
            expected_tx_mode = 0 if lossless else 1
            if fields["reduced_still_picture_header"] != 1 or fields.get("tx_mode", expected_tx_mode) != expected_tx_mode:
                raise RuntimeError(f"{name}: unexpected still-header or transform mode: {fields}")
            if lossless and fields["base_q_idx"] != 0:
                raise RuntimeError(f"{name}: lossless frame did not have qindex zero")
            disabled = (
                "use_128x128_superblock", "color_range", "color_description_present_flag", "mono_chrome",
                "using_qmatrix", "delta_q_present", "delta_q_y_dc.delta_coded",
                "delta_q_u_dc.delta_coded", "delta_q_u_ac.delta_coded",
            )
            if any(fields[field] for field in fields if field.startswith("enable_") or field in disabled):
                raise RuntimeError(f"{name}: unexpected sequence tools or color range: {fields}")
            if fields["seq_profile"] != (2 if bit_depth == 12 else 0) or fields["high_bitdepth"] != (bit_depth > 8):
                raise RuntimeError(f"{name}: unexpected profile or bit depth: {fields}")
            if bit_depth == 12:
                fields["twelve_bit"] = trace_value(trace, "twelve_bit")
                fields["subsampling_x"] = trace_value(trace, "subsampling_x")
                fields["subsampling_y"] = trace_value(trace, "subsampling_y")
                if any(fields[field] != 1 for field in ("twelve_bit", "subsampling_x", "subsampling_y")):
                    raise RuntimeError(f"{name}: expected 12-bit YUV420")
            if fields["max_frame_width_minus_1"] != 63 or fields["max_frame_height_minus_1"] != 63:
                raise RuntimeError(f"{name}: expected 64x64 sequence dimensions")
            loop_levels = [int(value) for value in re.findall(r"loop_filter_level\[\d+\]\s+[^=\n]+=\s*(\d+)", trace)]
            if (not lossless and not loop_levels) or any(loop_levels):
                raise RuntimeError(f"{name}: loop filtering was not disabled")
            reference = reference_path.read_bytes()
            if lossless and reference != input_path.read_bytes():
                raise RuntimeError(f"{name}: dav1d lossless reconstruction differs from the input samples")
            planes = unpack_planes(reference, bit_depth)
            expected_variable_planes = (0, 1, 2) if pattern == "mixed_yuv" else (0,)
            for plane in expected_variable_planes:
                if len(set(planes[plane])) == 1:
                    raise RuntimeError(f"{name}: plane {plane} lost all variation")
            plane_records = {}
            offset = 0
            sample_bytes = 1 if bit_depth == 8 else 2
            for plane, samples in zip(("y", "u", "v"), planes):
                byte_length = len(samples) * sample_bytes
                plane_records[plane] = {
                    "sample_count": len(samples), "byte_offset": offset, "byte_length": byte_length,
                    "sha256": sha256(reference[offset:offset + byte_length]),
                    "minimum": min(samples), "maximum": max(samples), "unique_count": len(set(samples)),
                }
                offset += byte_length
            stream = obu_path.read_bytes()
            records.append({
                "name": name, "bit_depth": bit_depth, "pixel_format": pixel_format,
                "quantizer": quantizer, "lossless": lossless,
                "transform_mode": "ONLY_4X4" if lossless else "ONLY_LARGEST",
                "transform_type": "WHT_WHT" if lossless else "DCT_DCT",
                "lossless_reference_matches_input": True if lossless else None,
                "input_pattern": PATTERNS[pattern], "pattern_scale": "1 << (bit_depth - 8)",
                "rounding": "Python round (ties to even)",
                "input_file": input_path.name, "input_sha256": sha256(input_path.read_bytes()),
                "obu_file": obu_path.name, "obu_bytes": len(stream), "obu_sha256": sha256(stream),
                "reference_file": reference_path.name, "reference_sha256": sha256(reference),
                "reference_planes": plane_records, "header_trace": fields, "loop_filter_levels": loop_levels,
                "color_matrix": 2, "color_matrix_note": "unspecified CICP uses the existing BT.601-family conversion",
                "commands": {"encode": encode, "decode_reference": decode, "trace_headers": trace_command},
            })
            test_cases.append({"name": name, "bit_depth": bit_depth, "stream": stream, "planes": planes})
            print(f"generated {name}: {len(stream)} OBU bytes; Y/U/V distinct samples {[len(set(p)) for p in planes]}", flush=True)
    formatted = run([args.moonfmt, "-"], input_text=generated_test(test_cases)).stdout
    args.test.write_text(formatted, encoding="utf-8", newline="\n")
    manifest = {
        "scope": "fixed 64x64 PARTITION_NONE: q30 ONLY_LARGEST DCT_DCT and lossless q0 ONLY_4X4 WHT fixtures; not general AV1 conformance",
        "dimensions": [WIDTH, HEIGHT], "format": "untouched aomenc low-overhead OBU; planar raw reference YUV",
        "generation_command": [sys.executable, *sys.argv],
        "encoder_version": encoder_version.group(0), "ffmpeg_version": ffmpeg_version,
        "decoder_version": f"libdav1d {dav1d_version}",
        "generated_test": str(args.test), "generated_test_sha256": sha256(args.test.read_bytes()),
        "reference_test_encoding": "lossless value/count RLE of every decoded sample, expanded before color conversion",
        "fixtures": records,
    }
    (args.out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(records)} fixtures and {args.test}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
