#!/usr/bin/env python3
"""Generate real AV1 partition/multiple-superblock references with dav1d planes.

The existing high-bit-depth generator supplies command execution and reference
serialization helpers. This corpus preserves aomenc output without OBU edits
and tests the complete public decode result against independent planar samples.
"""

from __future__ import annotations

import argparse
import importlib.util
import itertools
import json
import math
import re
import shutil
import struct
import sys
from pathlib import Path


# Loading the sibling generator must not leave untracked bytecode artifacts.
sys.dont_write_bytecode = True
helper_path = Path(__file__).with_name("generate-av1-highbd-ac-reference.py")
helper_spec = importlib.util.spec_from_file_location("av1_reference_helpers", helper_path)
assert helper_spec is not None and helper_spec.loader is not None
helpers = importlib.util.module_from_spec(helper_spec)
helper_spec.loader.exec_module(helpers)
run = helpers.run
sha256 = helpers.sha256

LAYOUTS = (
    ("split32_64x64", 64, 64, 32, 32, False, 30),
    ("split16_64x64", 64, 64, 16, 16, False, 30),
    ("split32_128x128", 128, 128, 32, 32, False, 30),
    ("adaptive_128x64", 128, 64, 16, 64, True, 30),
    ("split32_64x64", 64, 64, 32, 32, False, 0),
)
INPUT_PATTERN = {
    "scale": "1 << (bit_depth - 8)",
    "cx": "cos(pi * (x + 0.5) / plane_width)",
    "cy": "cos(pi * (y + 0.5) / plane_height)",
    "rx": "((x % period) + 0.5) / period - 0.5",
    "ry": "((y % period) + 0.5) / period - 0.5",
    "period": "32 for Y; 16 for U/V (same spatial cell in YUV420)",
    "y": "round(scale * (112 + 20*cx + 14*cy + 18*rx + 12*ry))",
    "u": "round(scale * (136 + 9*cx - 5*cy + 10*rx - 6*ry))",
    "v": "round(scale * (120 - 7*cx + 8*cy - 8*rx + 10*ry))",
    "rounding": "Python round, ties to even",
}


def input_planes(width: int, height: int, bit_depth: int) -> list[list[int]]:
    scale = 1 << (bit_depth - 8)
    planes = []
    for plane in range(3):
        pw, ph = (width, height) if plane == 0 else (width // 2, height // 2)
        period = 32 if plane == 0 else 16
        samples = []
        for y in range(ph):
            for x in range(pw):
                cx = math.cos(math.pi * (x + 0.5) / pw)
                cy = math.cos(math.pi * (y + 0.5) / ph)
                rx = ((x % period) + 0.5) / period - 0.5
                ry = ((y % period) + 0.5) / period - 0.5
                value = (
                    112 + 20 * cx + 14 * cy + 18 * rx + 12 * ry,
                    136 + 9 * cx - 5 * cy + 10 * rx - 6 * ry,
                    120 - 7 * cx + 8 * cy - 8 * rx + 10 * ry,
                )[plane]
                samples.append(round(scale * value))
        planes.append(samples)
    return planes


def unpack_planes(data: bytes, width: int, height: int, bit_depth: int) -> list[list[int]]:
    luma = width * height
    chroma = (width // 2) * (height // 2)
    count = luma + 2 * chroma
    expected_bytes = count * (1 if bit_depth == 8 else 2)
    if len(data) != expected_bytes:
        raise RuntimeError(f"decoded {len(data)} bytes; expected {expected_bytes}")
    values = list(data) if bit_depth == 8 else list(struct.unpack(f"<{count}H", data))
    if any(sample < 0 or sample >= 1 << bit_depth for sample in values):
        raise RuntimeError("decoded samples exceed the coded bit depth")
    return [values[:luma], values[luma:luma + chroma], values[luma + chroma:]]


def generate_test(cases: list[dict[str, object]]) -> str:
    source = """/// Generated by scripts/generate-av1-partition-reference.py.
/// Full dav1d planar references for untouched libaom partition fixtures.
/// The shared white-box helper compares every YUV sample and public RGBA pixel.
"""
    for case in cases:
        stream = case["stream"]
        rows = ["    " + ", ".join(f"b'\\x{value:02X}'" for value in stream[i:i + 12]) + "," for i in range(0, len(stream), 12)]
        source += f'\n///|\ntest "external libaom dav1d partition {case["name"]}" {{\n'
        source += "  let stream : Array[Byte] = [\n" + "\n".join(rows) + "\n  ]\n"
        for plane, samples in zip(("y", "u", "v"), case["planes"]):
            source += f"  let {plane}_runs : Array[Int] = " + helpers.array(helpers.rle(samples)) + "\n"
        source += f'  av1_reference_planes_compare(stream, {case["width"]}, {case["height"]}, {case["bit_depth"]}, y_runs, u_runs, v_runs)\n}}\n'
    return source


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("tests/fixtures/av1-partition"))
    parser.add_argument("--test", type=Path, default=Path("av1_partition_reference_wbtest.mbt"))
    parser.add_argument("--aomenc", default=shutil.which("aomenc") or "aomenc")
    parser.add_argument("--ffmpeg", default=shutil.which("ffmpeg") or "ffmpeg")
    parser.add_argument("--moonfmt", default=shutil.which("moonfmt") or "moonfmt")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    help_result = run([args.aomenc, "--help"])
    encoder_version = re.search(r"AOMedia Project AV1 Encoder[^\r\n]+", help_result.stdout + help_result.stderr)
    if encoder_version is None:
        raise RuntimeError("could not identify aomenc version")
    ffmpeg_version = run([args.ffmpeg, "-version"]).stdout.splitlines()
    dav1d_version = None
    records = []
    cases = []
    for bit_depth, layout in itertools.product((8, 10, 12), LAYOUTS):
        label, width, height, min_partition, max_partition, adaptive, quantizer = layout
        lossless = quantizer == 0
        name = f"{label}_{bit_depth}bit_q{quantizer}"
        input_path = args.out / f"{name}.input.yuv"
        obu_path = args.out / f"{name}.obu"
        reference_path = args.out / f"{name}.reference.yuv"
        input_data = helpers.pack_planes(input_planes(width, height, bit_depth), bit_depth)
        input_path.write_bytes(input_data)
        encode = [
            args.aomenc, "--debug", "--disable-warning-prompt", "--allintra", "--obu", "--i420",
            f"--width={width}", f"--height={height}", f"--profile={2 if bit_depth == 12 else 0}",
            f"--bit-depth={bit_depth}", f"--input-bit-depth={bit_depth}", "--fps=1/1", "--limit=1",
            "--cpu-used=0", "--threads=1", "--end-usage=q", f"--cq-level={quantizer}",
            f"--lossless={int(lossless)}", "--sb-size=64", "--tile-columns=0", "--tile-rows=0",
            "--aq-mode=0", "--deltaq-mode=0", "--enable-chroma-deltaq=0", "--enable-qm=0",
            "--enable-cdef=0", "--enable-restoration=0", "--enable-filter-intra=0",
            "--enable-intra-edge-filter=0", "--enable-angle-delta=0",
            f"--enable-rect-partitions={int(adaptive)}", f"--enable-1to4-partitions={int(adaptive)}",
            f"--enable-ab-partitions={int(adaptive)}", "--enable-smooth-intra=0",
            "--enable-paeth-intra=0", "--enable-palette=0", "--enable-flip-idtx=0",
            "--enable-tx64=1", "--enable-tx-size-search=0", "--use-intra-default-tx-only=1",
            f"--min-partition-size={min_partition}", f"--max-partition-size={max_partition}",
            "--enable-directional-intra=0", "--enable-cfl-intra=0", "--enable-intrabc=0",
            "--loopfilter-control=0", "-o", str(obu_path), str(input_path),
        ]
        run(encode)
        pixel_format = "yuv420p" if bit_depth == 8 else f"yuv420p{bit_depth}le"
        decode = [
            args.ffmpeg, "-hide_banner", "-loglevel", "verbose", "-y", "-c:v", "libdav1d",
            "-i", str(obu_path), "-frames:v", "1", "-f", "rawvideo", "-pix_fmt", pixel_format,
            str(reference_path),
        ]
        decoded = run(decode)
        decoder_versions = re.findall(r"libdav1d\s+([0-9][^\s]*)", decoded.stderr)
        if not decoder_versions or (dav1d_version is not None and dav1d_version != decoder_versions[0]):
            raise RuntimeError(f"{name}: missing or inconsistent libdav1d version")
        dav1d_version = decoder_versions[0]
        trace_command = [
            args.ffmpeg, "-hide_banner", "-i", str(obu_path), "-c", "copy", "-bsf:v", "trace_headers",
            "-f", "null", "-",
        ]
        trace = run(trace_command).stderr
        fields = {
            field: helpers.trace_value(trace, field)
            for field in (
                "seq_profile", "reduced_still_picture_header", "use_128x128_superblock",
                "enable_cdef", "enable_restoration", "enable_filter_intra", "enable_intra_edge_filter",
                "color_range", "color_description_present_flag", "mono_chrome", "high_bitdepth",
                "base_q_idx", "using_qmatrix", "segmentation_enabled",
                "max_frame_width_minus_1", "max_frame_height_minus_1",
                "delta_q_y_dc.delta_coded", "delta_q_u_dc.delta_coded", "delta_q_u_ac.delta_coded",
            )
        }
        disabled = (
            "use_128x128_superblock", "enable_cdef", "enable_restoration", "enable_filter_intra",
            "enable_intra_edge_filter", "color_range", "color_description_present_flag", "mono_chrome",
            "using_qmatrix", "segmentation_enabled", "delta_q_y_dc.delta_coded",
            "delta_q_u_dc.delta_coded", "delta_q_u_ac.delta_coded",
        )
        if fields["reduced_still_picture_header"] != 1 or any(fields[field] for field in disabled):
            raise RuntimeError(f"{name}: unexpected tools or still-picture header: {fields}")
        if fields["max_frame_width_minus_1"] != width - 1 or fields["max_frame_height_minus_1"] != height - 1:
            raise RuntimeError(f"{name}: sequence dimensions differ from requested layout")
        if fields["seq_profile"] != (2 if bit_depth == 12 else 0) or fields["high_bitdepth"] != (bit_depth > 8):
            raise RuntimeError(f"{name}: unexpected profile or bit depth")
        if bit_depth == 12:
            for field in ("twelve_bit", "subsampling_x", "subsampling_y"):
                fields[field] = helpers.trace_value(trace, field)
                if fields[field] != 1:
                    raise RuntimeError(f"{name}: expected 12-bit YUV420")
        if lossless:
            if fields["base_q_idx"] != 0:
                raise RuntimeError(f"{name}: expected qindex zero")
        else:
            fields["tx_mode"] = helpers.trace_value(trace, "tx_mode")
            fields["delta_q_present"] = helpers.trace_value(trace, "delta_q_present")
            if fields["tx_mode"] != 1 or fields["delta_q_present"] != 0:
                raise RuntimeError(f"{name}: expected ONLY_LARGEST without delta-q")
        loop_levels = [int(value) for value in re.findall(r"loop_filter_level\[\d+\]\s+[^=\n]+=\s*(\d+)", trace)]
        if any(loop_levels) or (not lossless and not loop_levels):
            raise RuntimeError(f"{name}: loop filtering is not disabled")
        reference = reference_path.read_bytes()
        if lossless and reference != input_data:
            raise RuntimeError(f"{name}: lossless reference differs from input")
        planes = unpack_planes(reference, width, height, bit_depth)
        if any(len(set(plane)) == 1 for plane in planes):
            raise RuntimeError(f"{name}: expected nonconstant Y, U and V planes")
        plane_records = {}
        offset = 0
        sample_bytes = 1 if bit_depth == 8 else 2
        for plane, values in zip(("y", "u", "v"), planes):
            byte_length = len(values) * sample_bytes
            plane_records[plane] = {
                "sample_count": len(values), "byte_offset": offset, "byte_length": byte_length,
                "sha256": sha256(reference[offset:offset + byte_length]),
                "minimum": min(values), "maximum": max(values), "unique_count": len(set(values)),
            }
            offset += byte_length
        stream = obu_path.read_bytes()
        records.append({
            "name": name, "dimensions": [width, height], "bit_depth": bit_depth, "pixel_format": pixel_format,
            "quantizer": quantizer, "lossless": lossless,
            "partition_constraints": {"minimum": min_partition, "maximum": max_partition, "rect_ab_1to4_allowed": adaptive},
            "partition_evidence": "encoder min=max and rectangle tools disabled force square split blocks" if not adaptive else "adaptive modes enabled; exact partition choices are not asserted without entropy tracing",
            "superblock_size": 64, "superblock_grid": [width // 64, height // 64],
            "transform_mode": "ONLY_4X4" if lossless else "ONLY_LARGEST",
            "transform_type": "WHT_WHT" if lossless else "DCT_DCT",
            "input_pattern": INPUT_PATTERN, "input_file": input_path.name, "input_sha256": sha256(input_data),
            "obu_file": obu_path.name, "obu_bytes": len(stream), "obu_sha256": sha256(stream),
            "reference_file": reference_path.name, "reference_sha256": sha256(reference), "reference_planes": plane_records,
            "lossless_reference_matches_input": True if lossless else None,
            "header_trace": fields, "loop_filter_levels": loop_levels,
            "color_matrix": 2, "color_matrix_note": "unspecified CICP uses the existing BT.601-family conversion",
            "commands": {"encode": encode, "decode_reference": decode, "trace_headers": trace_command},
        })
        cases.append({"name": name, "width": width, "height": height, "bit_depth": bit_depth, "stream": stream, "planes": planes})
        print(f"generated {name}: {len(stream)} OBU bytes; distinct Y/U/V samples {[len(set(plane)) for plane in planes]}", flush=True)
    formatted = run([args.moonfmt, "-"], input_text=generate_test(cases)).stdout
    args.test.write_text(formatted, encoding="utf-8", newline="\n")
    manifest = {
        "scope": "DC intra YUV420 fixed square partitions and adaptive partition layout, SB64, 8/10/12-bit; not general AV1 conformance",
        "format": "untouched aomenc low-overhead OBU; complete independent planar YUV decoded with libdav1d",
        "generation_command": [sys.executable, *sys.argv],
        "encoder_version": encoder_version.group(0), "ffmpeg_version": ffmpeg_version,
        "decoder_version": f"libdav1d {dav1d_version}",
        "generated_test": str(args.test), "generated_test_sha256": sha256(args.test.read_bytes()),
        "reference_test_encoding": "lossless value/count RLE; every coded-depth YUV sample and public RGBA pixel is compared by av1_reference_planes_wbtest.mbt",
        "fixtures": records,
    }
    (args.out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(records)} fixtures and {args.test}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
