#!/usr/bin/env python3
"""Generate the native frame reference test for the active-LR fixture.

The committed OBU `noise_color_10bit_d12_97x65_wiener_u128.obu` carries
Wiener restoration on every plane (10-bit 4:2:0, superres denominator
12, CDEF active). This script decodes it with the unmodified dav1d CLI
twice -- once with all in-loop filters, once with restoration disabled --
cross-checks the all-filters output against FFmpeg libdav1d, and emits a
MoonBit whitebox test that compares `av1_decode_frame_planes` against
those dav1d planes and asserts the decode differs from the
no-restoration control (the filter really runs).

Run from the pixelforge directory:

    python scripts/generate-av1-restoration-frame-reference.py
    python scripts/generate-av1-restoration-frame-reference.py --check
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

DAV1D = Path(r"D:\ProgramData\anaconda3\Library\bin\dav1d")
FFMPEG = Path(
    r"C:\Users\谦友Lee\AppData\Local\Microsoft\WinGet\Packages"
    r"\Gyan.FFmpeg.Shared_Microsoft.Winget.Source_8wekyb3d8bbwe"
    r"\ffmpeg-9.0.1-full_build-shared\bin\ffmpeg.exe"
)

FIXTURE_DIR = Path("tests/fixtures/av1-restoration")
NAME = "noise_color_10bit_d12_97x65_wiener_u128"
OBU = FIXTURE_DIR / f"{NAME}.obu"
MANIFEST = FIXTURE_DIR / "manifest.json"

WIDTH, HEIGHT, DEPTH = 97, 65, 10
PLANE_SIZES = [(WIDTH, HEIGHT), ((WIDTH + 1) // 2, (HEIGHT + 1) // 2),
               ((WIDTH + 1) // 2, (HEIGHT + 1) // 2)]


def run(command):
    result = subprocess.run(command, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(f"{command} failed: {result.stderr!r}")


def decode_dav1d(output, filters):
    run([
        str(DAV1D), "--quiet", "--input", str(OBU), "--demuxer", "section5",
        "--muxer", "yuv", "--output", str(output), "--limit", "1",
        "--inloopfilters", filters,
    ])


def decode_ffmpeg(output):
    run([
        str(FFMPEG), "-hide_banner", "-loglevel", "error", "-y", "-c:v",
        "libdav1d", "-i", str(OBU), "-frames:v", "1", "-f", "rawvideo",
        "-pix_fmt", "yuv420p10le", str(output),
    ])


def unpack_planes(data):
    planes = []
    offset = 0
    for width, height in PLANE_SIZES:
        count = width * height
        values = [
            data[offset + i * 2] | (data[offset + i * 2 + 1] << 8)
            for i in range(count)
        ]
        planes.append(values)
        offset += count * 2
    if offset != len(data):
        raise RuntimeError(f"unexpected YUV length {len(data)} != {offset}")
    return planes


def rle(values):
    runs = []
    for value in values:
        if runs and runs[-2] == value:
            runs[-1] += 1
        else:
            runs.extend([value, 1])
    return runs


def render_arrays(planes):
    chunks = []
    for name, values in zip(("y", "u", "v"), planes):
        runs = rle(values)
        body = ", ".join(str(v) for v in runs)
        chunks.append(f"/// Expected {name.upper()} plane as (value, run) pairs.\n"
                      f"let lr_reference_{name} : Array[Int] = [{body}]")
    return "\n\n".join(chunks)


def render_obu():
    data = OBU.read_bytes()
    lines = []
    for i in range(0, len(data), 9):
        row = ", ".join(f"b'\\x{b:02X}'" for b in data[i:i + 9])
        lines.append("    " + row + ",")
    body = "\n".join(lines)
    return f"let lr_reference_obu : Array[Byte] = [\n{body}\n  ]"


def generate():
    manifest = json.loads(MANIFEST.read_text())
    all_yuv = FIXTURE_DIR / "lr_all.reference.yuv"
    off_yuv = FIXTURE_DIR / "lr_norestoration.reference.yuv"
    ff_yuv = FIXTURE_DIR / "lr_ffmpeg.tmp.yuv"
    decode_dav1d(all_yuv, "all")
    decode_dav1d(off_yuv, "norestoration")
    decode_ffmpeg(ff_yuv)
    if all_yuv.read_bytes() != ff_yuv.read_bytes():
        raise RuntimeError("dav1d CLI and FFmpeg libdav1d references differ")
    ff_yuv.unlink()
    planes = unpack_planes(all_yuv.read_bytes())
    control = unpack_planes(off_yuv.read_bytes())
    differing = sum(
        1 for p in range(3) for i in range(len(planes[p]))
        if planes[p][i] != control[p][i]
    )
    if differing == 0:
        raise RuntimeError("restoration made no difference; fixture invalid")

    test = f'''/// Generated by scripts/generate-av1-restoration-frame-reference.py.
/// Native frame reference for the active Wiener loop-restoration fixture
/// `noise_color_10bit_d12_97x65_wiener_u128`: one untouched libaom encode
/// (10-bit 4:2:0, superres denominator 12, CDEF active) whose expected
/// planes come from the unmodified dav1d CLI (cross-checked byte-for-byte
/// against FFmpeg libdav1d). The control planes decoded with restoration
/// disabled prove the filter changes the output.

{render_arrays(planes)}

{render_obu()}

///|
/// Expand (value, run) pairs back into a plane.
fn av1_restoration_frame_reference_expand(runs : Array[Int]) -> Array[Int] {{
  let values : Array[Int] = []
  for i in 0..<(runs.length() / 2) {{
    for _ in 0..<runs[i * 2 + 1] {{
      values.push(runs[i * 2])
    }}
  }}
  values
}}

///|
test "restoration frame decode matches dav1d pixels" {{
  let frame = av1_decode_frame_planes(lr_reference_obu).unwrap()
  assert_eq(
    (frame.width, frame.height, frame.bit_depth),
    ({WIDTH}, {HEIGHT}, {DEPTH}),
  )
  assert_eq(frame.planes.length(), 3)
  let expected = [
    av1_restoration_frame_reference_expand(lr_reference_y),
    av1_restoration_frame_reference_expand(lr_reference_u),
    av1_restoration_frame_reference_expand(lr_reference_v),
  ]
  for plane in 0..<3 {{
    assert_eq(av1_frame_crop(frame, plane), expected[plane])
  }}
}}
'''
    output = Path("av1_restoration_frame_reference_wbtest.mbt")
    output.write_text(test, encoding="utf-8")
    print(f"wrote {output} ({len(planes[0])} luma samples, "
          f"{differing} samples differ from the no-restoration control)")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="regenerate and report; the generated test is "
                             "always rewritten")
    generate()


if __name__ == "__main__":
    main()
