"""Generate the separate_uv_delta_q white-box test.

The fixtures are two reduced-still 64x64 8-bit 4:2:0 streams that only differ
in quantization_params:

* ``uvdq_src.obu``      aomenc with --deltaq-mode=3 --enable-chroma-deltaq=1,
                        which emits non-zero U deltas (u_dc = u_ac = 2) while
                        leaving V to reuse them. Streams like this were
                        rejected before per-plane deltas were supported.
* ``uvdq_separate.obu`` the same stream rewritten by
                        ``_refs/make_uvdq_stream.py`` to signal
                        separate_uv_delta_q with diff_uv_delta = 1 and an
                        independent V pair (v_dc = 5, v_ac = -3). dav1d and
                        FFmpeg both decode it, and the rewrite with V = U
                        reproduces the source byte for byte, so the only
                        difference in the truth files is the V plane.

Every expectation is dav1d 1.2.1 output.
"""

import sys

DIR = "tests/fixtures/av1-uv-delta-q"
OUT = "av1_uv_delta_q_wbtest.mbt"


def moon_bytes(data, per_line=12):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append(
            "    " + ", ".join("b'\\x%02X'" % b for b in chunk) + ","
        )
    return "\n".join(lines)


def digest(samples):
    h = 0
    for i, s in enumerate(samples):
        v = s & 0xFF
        h ^= (v + (i & 0xFF))
        h = ((h << 5) & 0xFFFFFF) | ((h >> 19) & 0x1F)
        h &= 0xFFFFFF
    return h


def truth(name):
    d = open("%s/%s" % (DIR, name), "rb").read()[:6144]
    y, u, v = d[:4096], d[4096:5120], d[5120:]
    return (digest(y), digest(u), digest(v), list(y[:4]), list(u[:4]),
            list(v[:4]))


HEADER = '''/// Separate-uv-delta-q tests.
///
/// Generated by scripts/generate-av1-uv-delta-q-test.py from the fixtures in
/// tests/fixtures/av1-uv-delta-q. Every expectation is dav1d 1.2.1 output.
///
/// The two streams share their tile data: the second is the first rewritten to
/// signal separate_uv_delta_q with an independent V delta pair, so the only
/// plane that may differ between them is V. That isolates the V quantizer
/// index from the shared U one.

///|
fn av1_uvdq_stream_separate() -> Array[Byte] {
  [
'''

MIDDLE = '''  ]
}

///|
fn av1_uvdq_stream_shared() -> Array[Byte] {
  [
'''

FOOTER = '''  ]
}

///|
fn av1_uvdq_deltas(stream : Array[Byte]) -> (Int, Av1QuantDeltas) {
  let seq = av1_sequence_info(stream).unwrap()
  let frames = av1_obu_payloads(stream, 6)
  let frame = av1_parse_stage1_frame(frames[0], seq).unwrap()
  (frame.base_q_idx, frame.quant_deltas)
}

///|
/// The rewritten stream carries the diff flag and an independent V pair.
test "separate uv delta q parses an independent V delta pair" {
  let (base, deltas) = av1_uvdq_deltas(av1_uvdq_stream_separate())
  assert_eq(base, 32)
  assert_eq(deltas.y_dc, 0)
  assert_eq(deltas.u_dc, 2)
  assert_eq(deltas.u_ac, 2)
  assert_eq(deltas.v_dc, 5)
  assert_eq(deltas.v_ac, -3)
}

///|
/// Without the flag V simply mirrors U.
test "shared uv delta q mirrors the U deltas onto V" {
  let (base, deltas) = av1_uvdq_deltas(av1_uvdq_stream_shared())
  assert_eq(base, 32)
  assert_eq(deltas.u_dc, 2)
  assert_eq(deltas.u_ac, 2)
  assert_eq(deltas.v_dc, deltas.u_dc)
  assert_eq(deltas.v_ac, deltas.u_ac)
}

///|
/// Per-plane quantizer index arithmetic (AV1 7.12.3): luma AC keeps the base
/// index and every other index adds its delta before the [0, 255] clamp.
test "plane qindex applies the deltas and clamps" {
  let deltas : Av1QuantDeltas = {
    y_dc: 3,
    u_dc: 2,
    u_ac: 2,
    v_dc: 5,
    v_ac: -3,
  }
  assert_eq(av1_plane_qindex(32, deltas, 0, true), 35)
  assert_eq(av1_plane_qindex(32, deltas, 0, false), 32)
  assert_eq(av1_plane_qindex(32, deltas, 1, true), 34)
  assert_eq(av1_plane_qindex(32, deltas, 1, false), 34)
  assert_eq(av1_plane_qindex(32, deltas, 2, true), 37)
  assert_eq(av1_plane_qindex(32, deltas, 2, false), 29)
  assert_eq(av1_plane_qindex(1, deltas, 2, false), 0)
  assert_eq(av1_plane_qindex(253, deltas, 0, true), 255)
}

///|
/// End-to-end against dav1d: the stream with non-zero U deltas decodes
/// exactly, including the chroma planes whose dequant no longer uses the
/// luma index.
test "shared uv delta q stream matches dav1d pixel truth" {
  let frame = av1_decode_frame_planes(av1_uvdq_stream_shared()).unwrap()
  let y = av1_frame_crop(frame, 0)
  let u = av1_frame_crop(frame, 1)
  let v = av1_frame_crop(frame, 2)
  assert_eq(av1_plane_digest(y), 1288596)
  assert_eq(av1_plane_digest(u), 13048412)
  assert_eq(av1_plane_digest(v), 2383940)
  assert_eq(v[0], 96)
  assert_eq(v[1], 99)
  assert_eq(v[2], 102)
  assert_eq(v[3], 105)
}

///|
/// The same picture with an independent V pair: Y and U are unchanged and V
/// follows the new index, which no shared-delta code path can reproduce.
test "separate uv delta q stream matches dav1d pixel truth" {
  let frame = av1_decode_frame_planes(av1_uvdq_stream_separate()).unwrap()
  let y = av1_frame_crop(frame, 0)
  let u = av1_frame_crop(frame, 1)
  let v = av1_frame_crop(frame, 2)
  assert_eq(av1_plane_digest(y), 1288596)
  assert_eq(av1_plane_digest(u), 13048412)
  assert_eq(av1_plane_digest(v), 11314441)
  assert_eq(v[0], 98)
  assert_eq(v[1], 100)
  assert_eq(v[2], 104)
  assert_eq(v[3], 106)
}
'''


def main():
    sep = open("%s/uvdq_separate.obu" % DIR, "rb").read()
    shared = open("%s/uvdq_src.obu" % DIR, "rb").read()
    body = (
        HEADER
        + moon_bytes(sep)
        + "\n"
        + MIDDLE
        + moon_bytes(shared)
        + "\n"
        + FOOTER
    )
    open(OUT, "w", newline="\n").write(body)
    print("wrote", OUT)
    for name in ("uvdq_src_truth.yuv", "uvdq_separate_truth.yuv"):
        t = truth(name)
        print("  %-22s Y=%d U=%d V=%d" % (name, t[0], t[1], t[2]))


if __name__ == "__main__":
    sys.exit(main())
