#!/usr/bin/env python3
"""Pin SGR arithmetic with unmodified native dav1d 1.2.1 filter kernels.

Python 3, a C compiler and standalone moonfmt are required. --source-dir
points to dav1d/src; absent sources download from its official release tag.
--check regenerates only in temporary storage and compares the embedded WB.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import shutil
import subprocess
import tempfile
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
HASHES = {
    "looprestoration_tmpl.c": "efe1c27fa9518c448db7704f0d291968c74b4e4e6d01376cfe5bee6911e4e6fb",
    "tables.c": "a602f9d8c59da436ccdeec6afc279a72248d4840d97e5ab42d9ab6170a8374c5",
}


def braced(source: str, marker: str) -> str:
    start = source.index(marker)
    end = source.index("{", start)+1
    depth = 1
    while depth:
        depth += (source[end] == "{") - (source[end] == "}")
        end += 1
    return source[start:end]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=Path(tempfile.gettempdir()) / "pixelforge-dav1d-sgr-1.2.1")
    tcc = Path.home() / ".moon/bin/internal/tcc.exe"
    parser.add_argument("--cc", default=shutil.which("cc") or shutil.which("gcc") or str(tcc))
    parser.add_argument("--moonfmt", default=shutil.which("moonfmt") or "moonfmt")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sources = {}
    for name, expected in HASHES.items():
        path = args.source_dir/name
        data = path.read_bytes() if path.exists() else urllib.request.urlopen("https://raw.githubusercontent.com/videolan/dav1d/1.2.1/src/"+name,timeout=60).read()
        if hashlib.sha256(data).hexdigest() != expected:
            raise RuntimeError(f"Unexpected {name} source hash")
        sources[name] = data.decode("utf8")
    source = sources["looprestoration_tmpl.c"]
    c = """typedef unsigned char uint8_t;
typedef unsigned short pixel;
typedef int int32_t;
typedef int coef;
typedef long long ptrdiff_t;
extern int printf(const char *, ...);
#define ALIGN(name,alignment) name
#define NOINLINE
#define REST_UNIT_STRIDE 390
#define HIGHBD_DECL_SUFFIX , const int bitdepth_max
#define imax(a,b) ((a)>(b)?(a):(b))
#define umin(a,b) ((a)<(b)?(a):(b))
static int bitdepth_from_max(int value) { return value==255 ? 8 : value==1023 ? 10 : 12; }
"""
    c += braced(sources["tables.c"],"const uint8_t ALIGN(dav1d_sgr_x_by_x[")+";\n"
    c += braced(source,"static void boxsum3(")+"\n"
    c += braced(source,"static void boxsum5(")+"\n"
    c += braced(source,"static NOINLINE void\nselfguided_filter(")+"\n"
    cases = [(depth,pattern,r,eps) for depth in (8,10,12) for pattern in (0,1) for r,eps in ((1,4),(1,6),(2,12))]
    c += "int main(void) { static pixel src[68*390]; static coef dst[64*384];\n"
    for depth,pattern,r,eps in cases:
        maximum=(1<<depth)-1
        c += f"{{ const int maximum={maximum},pattern={pattern};\n"
        c += "for(int y=0;y<14;y++)for(int x=0;x<14;x++){int yy=y<3?0:y>10?7:y-3;int xx=x<3?0:x>10?7:x-3;src[y*390+x]=pattern?(((xx+yy)&1)?maximum:0):maximum;}\n"
        n=(r*2+1)**2
        strength=((1<<20)+n*n*eps//2)//(n*n*eps)
        c += f"selfguided_filter(dst,src,390,8,8,{n},{strength},{maximum});\n"
        c += 'for(int y=0;y<8;y++)for(int x=0;x<8;x++)printf("%d ",dst[y*384+x]+(src[(y+3)*390+x+3]<<4));printf("\\n");}\n'
    c += "return 0;}\n"
    with tempfile.TemporaryDirectory(prefix="pixelforge-sgr-native-") as temp:
        path=Path(temp)
        (path/"oracle.c").write_text(c,encoding="utf8")
        command=[args.cc]
        compiler=Path(args.cc).resolve()
        moon_root=compiler.parent.parent.parent
        if compiler.parent.name=="internal" and (moon_root/"lib/libtcc1.a").exists():
            command += ["-B",str(moon_root)]
        command += ["-std=c99",str(path/"oracle.c"),"-o",str(path/"oracle.exe")]
        subprocess.run(command,check=True)
        rows=[list(map(int,line.split())) for line in subprocess.check_output([str(path/"oracle.exe")],text=True).splitlines()]
    if len(rows)!=len(cases) or any(len(row)!=64 for row in rows):
        raise RuntimeError("Incomplete native SGR output")
    text=["// Generated by scripts/generate-av1-sgr-reference.py.",
          "// Original dav1d 1.2.1 boxsum3, boxsum5, selfguided_filter and x_by_x table.",
          "// looprestoration_tmpl.c SHA256: "+HASHES["looprestoration_tmpl.c"],
          "// tables.c SHA256: "+HASHES["tables.c"], ""]
    for (depth,pattern,r,eps),expected in zip(cases,rows):
        text += ["///|",f'test "native SGR unsigned statistics {depth}bit pattern{pattern} radius{r} eps{eps}" {{',
                 f"  let maximum = {(1<<depth)-1}",
                 ("  let input = Array::makei(64, fn(i) { if ((i / 8 + i % 8) & 1) != 0 { maximum } else { 0 } })" if pattern else "  let input = Array::make(64, maximum)"),
                 f"  let store = av1_restoration_save_stripes([input], 8, 8, 8, 8, {depth}, true).unwrap()",
                 "  let view = av1_filter_test_view(store, input, 8)",
                 f"  let actual = av1_sgr_box_pass(view, 0, 0, 0, 8, 8, 0, {r}, {eps}, {0 if r==2 else 1}, {depth}).unwrap()",
                 "  let expected = ["+",".join(map(str,expected))+"]",
                 "  assert_eq(actual, expected)","}",""]
    formatted=subprocess.run([args.moonfmt,"-"],input="\n".join(text),encoding="utf8",text=True,capture_output=True,check=True).stdout
    output=ROOT/"av1_sgr_unsigned_reference_wbtest.mbt"
    if args.check:
        if output.read_text(encoding="utf8")!=formatted:
            raise RuntimeError("SGR native reference changed")
    else:
        output.write_text(formatted,encoding="utf8",newline="\n")
    print(f"Verified {len(cases)} native SGR cases / {len(cases)*64} coefficients."+(" Generated file matches." if args.check else " Generated WB test."))


if __name__=="__main__":
    main()
