#!/usr/bin/env python3
"""Generate unmodified libaom multi-tile OBU streams and dav1d plane references.

Each tile is one 64x64 superblock with a distinct constant luma and neutral
chroma. The generated MoonBit tests compare every decoded pixel with RGBA
converted by PixelForge from the independently decoded dav1d YUV samples.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import tempfile
from pathlib import Path


GEOMETRIES = ((128, 64, 1, 0), (64, 128, 0, 1), (128, 128, 1, 1))
LUMA_8BIT = (64, 96, 160, 192)
ENCODER_OPTIONS = [
    "--allintra", "--obu", "--debug", "--i420", "--fps=1/1", "--limit=1",
    "--cpu-used=0", "--threads=1", "--end-usage=q", "--cq-level=10", "--sb-size=64",
    "--enable-cdef=0", "--enable-restoration=0", "--loopfilter-control=0",
    "--enable-filter-intra=0", "--enable-intra-edge-filter=0", "--enable-angle-delta=0",
    "--enable-directional-intra=0", "--enable-smooth-intra=0", "--enable-paeth-intra=0",
    "--enable-palette=0", "--enable-cfl-intra=0", "--enable-intrabc=0",
    "--enable-rect-partitions=0", "--enable-1to4-partitions=0", "--enable-ab-partitions=0",
    "--enable-flip-idtx=0", "--enable-tx64=1", "--enable-tx-size-search=0",
    "--use-intra-default-tx-only=1", "--use-intra-dct-only=1",
    "--min-partition-size=64", "--max-partition-size=64", "--deltaq-mode=0",
]


def run(command: list[str]) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(command, text=True, capture_output=True)
    if result.returncode:
        raise RuntimeError(f"command failed ({result.returncode}): {command}\n{result.stdout}\n{result.stderr}")
    return result


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def executable_info(executable: str, version: str) -> dict[str, str]:
    path = Path(shutil.which(executable) or executable).resolve()
    return {"path": str(path), "sha256": sha256(path.read_bytes()), "version": version.strip()}


def source_planes(width: int, height: int, bit_depth: int) -> tuple[list[int], list[int], list[int]]:
    scale = 1 << (bit_depth - 8)
    tile_cols = width // 64
    y = [LUMA_8BIT[(row // 64) * tile_cols + col // 64] * scale
         for row in range(height) for col in range(width)]
    neutral = 1 << (bit_depth - 1)
    chroma = [neutral] * (width * height // 4)
    return y, chroma, chroma.copy()


def encode_samples(planes: tuple[list[int], list[int], list[int]], bit_depth: int) -> bytes:
    values = [value for plane in planes for value in plane]
    return bytes(values) if bit_depth == 8 else struct.pack(f"<{len(values)}H", *values)


def decode_samples(data: bytes, bit_depth: int) -> list[int]:
    if bit_depth == 8:
        return list(data)
    if len(data) % 2:
        raise RuntimeError("dav1d output has an incomplete high-bit-depth sample")
    return list(struct.unpack(f"<{len(data) // 2}H", data))


def tile_constants(samples: list[int], width: int, height: int) -> list[dict[str, int]]:
    y_size = width * height
    chroma_width = width // 2
    chroma_size = y_size // 4
    planes = (samples[:y_size], samples[y_size:y_size + chroma_size], samples[y_size + chroma_size:])
    tiles = []
    for row in range(height // 64):
        for col in range(width // 64):
            values = []
            for plane_no, plane in enumerate(planes):
                side = 64 if plane_no == 0 else 32
                stride = width if plane_no == 0 else chroma_width
                unique = {plane[(row * side + y) * stride + col * side + x]
                          for y in range(side) for x in range(side)}
                if len(unique) != 1:
                    raise RuntimeError(f"dav1d tile ({row}, {col}) plane {plane_no} is not constant: {sorted(unique)}")
                values.append(next(iter(unique)))
            tiles.append({"row": row, "col": col, "y": values[0], "u": values[1], "v": values[2]})
    return tiles


def trace_values(trace: str, name: str) -> list[int]:
    return [int(value) for value in re.findall(rf"\b{re.escape(name)}\s+[^=\n]+=\s*(\d+)", trace)]


def normalize_command(command: list[str], work: Path) -> list[str]:
    # Only ephemeral filenames are normalized; the actual executable and all
    # options used for this run remain present in the manifest.
    return [arg.replace(str(work), "{work_dir}") for arg in command]


def moon_bytes(data: bytes) -> str:
    values = [f"b'\\x{byte:02X}'" for byte in data]
    return "\n".join("    " + ", ".join(values[start:start + 9]) + "," for start in range(0, len(values), 9))


def moon_tests(records: list[dict[str, object]]) -> str:
    text = [
        "/// Generated by scripts/generate-av1-multitile-reference.py.",
        "/// OBU bytes are unmodified libaom output. Expected tile planes were",
        "/// independently decoded with libdav1d; see the fixture manifest.",
        "fn av1_multitile_reference_expected(",
        "  width : Int, height : Int, bit_depth : Int, values : Array[(Int, Int, Int)],",
        ") -> Image {",
        "  let y = Array::make(width * height, 0)",
        "  let u = Array::make(width * height / 4, 0)",
        "  let v = Array::make(width * height / 4, 0)",
        "  let cols = width / 64",
        "  for index in 0..<values.length() {",
        "    let (yv, uv, vv) = values[index]",
        "    let row = index / cols",
        "    let col = index % cols",
        "    for py in 0..<64 { for px in 0..<64 {",
        "      y[(row * 64 + py) * width + col * 64 + px] = yv",
        "    }}",
        "    for py in 0..<32 { for px in 0..<32 {",
        "      let offset = (row * 32 + py) * (width / 2) + col * 32 + px",
        "      u[offset] = uv",
        "      v[offset] = vv",
        "    }}",
        "  }",
        "  av1_yuv420_highbd_to_rgba(width, height, y, u, v, bit_depth).unwrap()",
        "}",
        "",
    ]
    for record in records:
        width, height = record["dimensions"]
        bit_depth = record["bit_depth"]
        tiles = record["decoded_tiles"]
        values = ", ".join(f"({tile['y']}, {tile['u']}, {tile['v']})" for tile in tiles)
        text.extend([
            "///|", f"test \"external libaom multi-tile {record['name']}\" {{",
            "  let stream : Array[Byte] = [", moon_bytes(bytes.fromhex(record["obu_hex"])), "  ]",
            "  let actual = av1_decode(stream).unwrap()",
            f"  let expected = av1_multitile_reference_expected({width}, {height}, {bit_depth}, [{values}])",
            f"  assert_eq((actual.width, actual.height), ({width}, {height}))",
            f"  for y in 0..<{height} {{ for x in 0..<{width} {{",
            "    assert_eq(actual.get_pixel(x, y), expected.get_pixel(x, y))",
            "  }}", "}", "",
        ])
    return "\n".join(text)


def canonical_moon_tests(records: list[dict[str, object]], moonfmt: str) -> bytes:
    """Format only the generated source; never invoke package-wide moon fmt."""
    result = subprocess.run(
        [moonfmt, "-"], input=moon_tests(records).encode("utf-8"), capture_output=True,
    )
    if result.returncode:
        raise RuntimeError(f"moonfmt failed ({result.returncode}): {result.stderr.decode('utf-8', errors='replace')}")
    # moonfmt writes platform line endings to stdout; generated sources use
    # LF so regeneration is byte-identical on Windows and Unix.
    return result.stdout.replace(b"\r\n", b"\n")


def write_if_different(path: Path, data: bytes) -> None:
    if not path.is_file() or path.read_bytes() != data:
        path.write_bytes(data)


def check_generated(
    output: Path, moon_test: Path, records: list[dict[str, object]], source: bytes,
) -> None:
    """Compare regenerated content, ignoring commands' host/temporary paths."""
    manifest = json.loads((output / "manifest.json").read_text(encoding="utf-8"))
    expected = {record["name"]: record for record in manifest["fixtures"]}
    if set(expected) != {record["name"] for record in records}:
        raise RuntimeError("generated fixture names differ from the checked-in manifest")
    command_fields = {"encoder_command", "decoder_command", "trace_command"}
    for record in records:
        name = record["name"]
        for key, value in record.items():
            if key not in command_fields and expected[name].get(key) != value:
                raise RuntimeError(f"{name}: regenerated manifest field {key} differs")
        path = output / f"{name}.obu"
        if path.read_bytes() != bytes.fromhex(record["obu_hex"]):
            raise RuntimeError(f"{path}: regenerated OBU bytes differ")
    if moon_test.read_bytes() != source:
        raise RuntimeError(f"{moon_test}: generated moonfmt output differs")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("tests/fixtures/av1-multitile"))
    parser.add_argument("--moon-test", type=Path, default=Path("av1_multitile_reference_test.mbt"))
    parser.add_argument("--aomenc", default=shutil.which("aomenc") or "aomenc")
    parser.add_argument("--ffmpeg", default=shutil.which("ffmpeg") or "ffmpeg")
    parser.add_argument("--moonfmt", default=shutil.which("moonfmt") or "moonfmt")
    parser.add_argument("--bit-depths", type=int, nargs="+", default=[8, 10, 12])
    parser.add_argument("--check", action="store_true", help="regenerate in temporary storage and compare existing fixtures/tests without writing")
    args = parser.parse_args()
    if any(depth not in (8, 10, 12) for depth in args.bit_depths):
        parser.error("bit depths must be 8, 10, or 12")
    if not args.check:
        args.out.mkdir(parents=True, exist_ok=True)
    aom_help = run([args.aomenc, "--help"])
    encoder_version = next(line.strip() for line in aom_help.stdout.splitlines()
                           if "AOMedia Project AV1 Encoder" in line)
    ffmpeg_version = run([args.ffmpeg, "-version"]).stdout
    records: list[dict[str, object]] = []
    decoder_versions: set[str] = set()
    with tempfile.TemporaryDirectory(prefix="av1-multitile-reference-") as temporary:
        work = Path(temporary)
        for bit_depth in args.bit_depths:
            for width, height, cols_log2, rows_log2 in GEOMETRIES:
                name = f"tiles{1 << cols_log2}x{1 << rows_log2}_{bit_depth}bit_q10"
                source = work / f"{name}.yuv"
                output = work / f"{name}.obu"
                decoded_path = work / f"{name}.decoded.yuv"
                source_data = encode_samples(source_planes(width, height, bit_depth), bit_depth)
                source.write_bytes(source_data)
                encoder_command = [args.aomenc, *ENCODER_OPTIONS,
                    f"--width={width}", f"--height={height}", f"--profile={2 if bit_depth == 12 else 0}",
                    f"--bit-depth={bit_depth}", f"--input-bit-depth={bit_depth}",
                    f"--tile-columns={cols_log2}", f"--tile-rows={rows_log2}",
                    "-o", str(output), str(source)]
                run(encoder_command)
                pix_fmt = "yuv420p" if bit_depth == 8 else f"yuv420p{bit_depth}le"
                decoder_command = [args.ffmpeg, "-hide_banner", "-loglevel", "verbose", "-y",
                    "-c:v", "libdav1d", "-i", str(output), "-frames:v", "1", "-f", "rawvideo",
                    "-pix_fmt", pix_fmt, str(decoded_path)]
                decoded_run = run(decoder_command)
                decoder_versions.update(re.findall(r"libdav1d ([0-9][^\s]*)", decoded_run.stderr))
                decoded_data = decoded_path.read_bytes()
                expected_size = width * height * 3 // 2 * (1 if bit_depth == 8 else 2)
                if len(decoded_data) != expected_size:
                    raise RuntimeError(f"{name}: decoded size {len(decoded_data)} != {expected_size}")
                decoded_tiles = tile_constants(decode_samples(decoded_data, bit_depth), width, height)
                trace_command = [args.ffmpeg, "-hide_banner", "-i", str(output), "-c", "copy",
                    "-bsf:v", "trace_headers", "-f", "null", os.devnull]
                traced = run(trace_command)
                trace = traced.stdout + traced.stderr
                expected_flags = {
                    "reduced_still_picture_header": 1, "use_128x128_superblock": 0,
                    "enable_cdef": 0, "enable_restoration": 0, "enable_filter_intra": 0,
                    "enable_intra_edge_filter": 0, "uniform_tile_spacing_flag": 1, "tx_mode": 1,
                    "tile_cols_log2": cols_log2, "tile_rows_log2": rows_log2,
                    "tile_start_and_end_present_flag": 0, "color_range": 0,
                    "max_frame_width_minus_1": width - 1, "max_frame_height_minus_1": height - 1,
                }
                trace_flags = {key: trace_values(trace, key) for key in expected_flags}
                for key, expected in expected_flags.items():
                    if not trace_flags[key] or any(value != expected for value in trace_flags[key]):
                        raise RuntimeError(f"{name}: expected {key}={expected}, got {trace_flags[key]}\n{trace}")
                loop_levels = [int(value) for value in re.findall(r"loop_filter_level\[\d+\]\s+[^=\n]+=\s*(\d+)", trace)]
                if not loop_levels or any(loop_levels):
                    raise RuntimeError(f"{name}: loop filter was not disabled: {loop_levels}")
                qidx = trace_values(trace, "base_q_idx")
                if len(qidx) != 1:
                    raise RuntimeError(f"{name}: missing or ambiguous qindex: {qidx}")
                obu = output.read_bytes()
                records.append({
                    "name": name, "dimensions": [width, height], "bit_depth": bit_depth,
                    "pixel_format": pix_fmt, "tile_cols_log2": cols_log2, "tile_rows_log2": rows_log2,
                    "source_tile_luma": [LUMA_8BIT[index] << (bit_depth - 8) for index in range(len(decoded_tiles))],
                    "source_chroma": 1 << (bit_depth - 1), "source_sha256": sha256(source_data),
                    "encoder_command": normalize_command(encoder_command, work),
                    "decoder_command": normalize_command(decoder_command, work),
                    "trace_command": normalize_command(trace_command, work), "trace_flags": trace_flags,
                    "loop_filter_levels": loop_levels, "qidx": qidx[0],
                    "obu_bytes": len(obu), "obu_sha256": sha256(obu), "obu_hex": obu.hex(),
                    "decoded_sha256": sha256(decoded_data), "decoded_tiles": decoded_tiles,
                })
                print(f"verified {name}: {len(obu)} OBU bytes; dav1d tiles {decoded_tiles}")
    manifest = {
        "format": "AV1 low-overhead OBU; unmodified encoder output",
        "generation_command": "python scripts/generate-av1-multitile-reference.py --aomenc <path-to-aomenc>",
        "command_path_note": "{work_dir} replaces only ephemeral temporary directory paths in actual command arguments",
        "encoder": executable_info(args.aomenc, encoder_version),
        "decoder": executable_info(args.ffmpeg, ffmpeg_version),
        "libdav1d_versions": sorted(decoder_versions),
        "pixel_comparison": "every RGBA pixel after applying PixelForge YUV conversion to independently decoded dav1d tile constants",
        "fixtures": records,
    }
    if not decoder_versions:
        raise RuntimeError("ffmpeg did not report the independent libdav1d version")
    source = canonical_moon_tests(records, args.moonfmt)
    if args.check:
        check_generated(args.out, args.moon_test, records, source)
        print(f"checked {len(records)} regenerated OBU/manifest records and canonical {args.moon_test}")
        return 0
    for record in records:
        write_if_different(args.out / f"{record['name']}.obu", bytes.fromhex(record["obu_hex"]))
    write_if_different(args.out / "manifest.json", (json.dumps(manifest, indent=2) + "\n").encode("utf-8"))
    write_if_different(args.moon_test, source)
    print(f"generated {len(records)} fixtures and {args.moon_test}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
