#!/usr/bin/env python3
"""Generate the AV1 subpel interpolation filter table from the cached go-av1 source.

    python scripts/generate-av1-interp-tables.py
    python scripts/generate-av1-interp-tables.py --check

`subpelFilters[filter_type][fractional_pel][8]` is the normative Subpel_Filters
table (AV1 §7.11.3.4). The source hash is pinned so a changed cache cannot
silently alter motion compensation. These are plain coefficient rows, not CDFs,
so nothing here needs to be freshly allocated per tile.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "_refs", "go-av1", "decode", "subpel_gen.go")
OUTPUT = os.path.join(ROOT, "av1_interp_tables.mbt")
MOONFMT = os.path.join(os.path.expanduser("~"), ".moon", "bin", "moonfmt")

URL = "https://github.com/mgvs/go-av1/tree/main/decode"

LICENSE = """// BSD 2-Clause License
//
// Copyright (c) 2026, Oleksandr Zhabotynskyi
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE."""


def parse_table(text: str) -> list[list[list[int]]]:
    """Read `var subpelFilters = [6][16][8]int{...}` into nested lists."""
    start = text.index("subpelFilters")
    brace = text.index("{", start)
    depth = 0
    for index in range(brace, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                end = index + 1
                break
    else:
        raise SystemExit("unterminated subpelFilters literal")
    body = text[brace:end]
    rows = re.findall(r"\{(-?\d+(?:,\s*-?\d+){7})\}", body)
    if len(rows) != 6 * 16:
        raise SystemExit("expected 96 eight-tap rows, found %d" % len(rows))
    table = []
    for group in range(6):
        filters = []
        for phase in range(16):
            taps = [int(v) for v in rows[group * 16 + phase].split(",")]
            assert len(taps) == 8
            filters.append(taps)
        table.append(filters)
    return table


def render(table: list[list[list[int]]], digest: str) -> str:
    parts = [
        "// Generated by scripts/generate-av1-interp-tables.py. Do not edit.",
        "// AV1 Subpel_Filters: [filter_type][fractional_pel (1/16 units)][8 taps].",
        "// Source: %s" % URL,
        "// _refs/go-av1/decode/subpel_gen.go SHA-256: %s" % digest,
        "//",
        LICENSE,
        "",
        "///|",
        "/// Normative eight-tap interpolation kernels (AV1 §7.11.3.4). Index 0",
        "/// is the identity pass-through used for a zero vector; sets 0..2 are",
        "/// the eight-tap smooth/sharp/standard filters, 3 is the two-tap",
        "/// bilinear filter, and 4..5 are the four-tap substitutes narrow blocks",
        "/// are forced onto.",
        "let av1_subpel_filters : Array[Array[Array[Int]]] = [",
    ]
    for group in table:
        parts.append("  [")
        for phase in group:
            parts.append("    [%s]," % ", ".join(str(v) for v in phase))
        parts.append("  ],")
    parts.append("]")
    return "\n".join(parts) + "\n"


def format_source(source: str) -> str:
    if not os.path.exists(MOONFMT):
        return source
    proc = subprocess.run(
        [MOONFMT, "-w"],
        input=source,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return proc.stdout or source


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = open(SOURCE, "rb").read()
    digest = hashlib.sha256(raw).hexdigest()
    rendered = format_source(render(parse_table(raw.decode("utf-8")), digest))
    if args.check:
        current = open(OUTPUT, encoding="utf-8").read()
        if current != rendered:
            raise SystemExit("%s is stale; regenerate it" % os.path.basename(OUTPUT))
        print("%s matches the pinned source" % os.path.basename(OUTPUT))
        return
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(rendered)
    print("wrote %s (%d bytes, source %s)" % (OUTPUT, len(rendered), digest[:12]))


if __name__ == "__main__":
    main()
